spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1 saat (milisaniye cinsinden)
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      repositories:
        enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      retry-backoff-ms: 1000
      acks: all
      max-in-flight-requests: 5
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      # Consumer Group Yönetimi - Performans ve Güvenilirlik
      max-poll-records: 500  # Her poll'da maksimum mesaj sayısı (batch processing)
      max-poll-interval-ms: 300000  # 5 dakika - Mesaj işleme süresi limiti
      session-timeout-ms: 30000  # 30 saniye - Consumer çöktüğünde tespit süresi
      heartbeat-interval-ms: 10000  # 10 saniye - Consumer'ın aktif olduğunu gösterir
      fetch-min-size: 1  # Minimum fetch size (bytes)
      fetch-max-wait: 500  # Maximum fetch wait time (ms)
      # Offset commit stratejisi
      auto-commit-interval-ms: 5000  # 5 saniyede bir offset commit
      # Consumer group rebalance ayarları
      partition-assignment-strategy: org.apache.kafka.clients.consumer.RangeAssignor

server:
  port: 9016

app:
  kafka:
    transaction-topic: transaction-events
    dlq-topic: transaction-events-dlq  # Dead Letter Queue topic
    # Consumer Group ID'leri
    consumer-groups:
      notification-group: notification-group  # Transaction event'leri için
      dlq-handler-group: dlq-handler-group  # DLQ mesajları için

customer:
  service:
    url: http://localhost:9017

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    com.example.OnlineBankacilik: INFO
    com.example.OnlineBankacilik.Kafka: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      customerService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
  retry:
    instances:
      customerService:
        maxAttempts: 3
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.SocketTimeoutException
          - java.util.concurrent.TimeoutException
  timelimiter:
    instances:
      customerService:
        timeoutDuration: 5s
        cancelRunningFuture: true

# Feign Client Configuration
feign:
  client:
    config:
      customer-service:
        connectTimeout: 2000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true
  resilience4j:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,kafka
  metrics:
    export:
      prometheus:
        enabled: true

